(()=>{
const C=window.TRANSFERS_CONFIG||{},live=!!(C.supabaseUrl&&C.supabaseAnonKey),sb=live?window.supabase.createClient(C.supabaseUrl,C.supabaseAnonKey):null;
let user=null,profile=null,items=[],presence=null;
const $=id=>document.getElementById(id),E={form:$("form"),edit:$("editId"),date:$("date"),time:$("time"),driver:$("driver"),drivers:$("drivers"),origin:$("origin"),destination:$("destination"),pallet:$("pallet"),job:$("job"),save:$("save"),del:$("delete"),cancel:$("cancel"),msg:$("msg"),boardDate:$("boardDate"),grid:$("grid"),title:$("title"),mode:$("mode"),me:$("me"),email:$("email"),active:$("active"),login:$("login"),loginForm:$("loginForm"),loginEmail:$("loginEmail"),loginPassword:$("loginPassword"),loginMsg:$("loginMsg"),signout:$("signout"),formTitle:$("formTitle")};
const key="transfers-demo-v1",today=()=>{let d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)},add=(iso,n)=>{let d=new Date(iso+"T12:00:00");d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)},fmt=t=>{let a=t.slice(0,5).split(":").map(Number),h=a[0],m=a[1];return (h%12||12)+":"+String(m).padStart(2,"0")+" "+(h>=12?"PM":"AM")};
function name(){return profile?.display_name||user?.user_metadata?.display_name||user?.email?.split("@")[0]||"User"}
function msg(s,c){E.msg.textContent=s||"";E.msg.style.color=c==="error"?"#a43c3c":c==="ok"?"#2f6f49":""}
function normalize(x){return{id:String(x.id),scheduled_date:x.scheduled_date,scheduled_time:String(x.scheduled_time||"00:00").slice(0,5),driver:x.driver||"Unassigned",origin:x.origin||"",destination:x.destination||"",pallet_count:Number(x.pallet_count||0),job_number:x.job_number||"",created_by:x.created_by,created_by_name:x.created_by_name||"Unknown"}}
function saveLocal(){localStorage.setItem(key,JSON.stringify(items))}
function loadLocal(){try{items=(JSON.parse(localStorage.getItem(key)||"[]")||[]).map(normalize)}catch{items=[]}}
function renderDrivers(){let d=[...new Set(items.map(x=>x.driver).filter(Boolean))].sort();E.drivers.innerHTML=d.map(x=>'<option value="'+x.replace(/"/g,"&quot;")+'"></option>').join("")}
function renderBoard(){
 let date=E.boardDate.value,day=items.filter(x=>x.scheduled_date===date),drivers=[...new Set(day.map(x=>x.driver))].sort();
 E.title.textContent=new Date(date+"T12:00:00").toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric",year:"numeric"});
 E.grid.innerHTML="";
 let hr=document.createElement("div");hr.className="headrow";let c=document.createElement("div");c.className="corner";c.textContent="Time";hr.appendChild(c);
 if(!drivers.length){let d=document.createElement("div");d.className="driverhead";d.textContent="No transfers scheduled";hr.appendChild(d)}
 drivers.forEach(d=>{let h=document.createElement("div");h.className="driverhead";h.textContent=d;hr.appendChild(h)});E.grid.appendChild(hr);
 let br=document.createElement("div");br.className="bodyrow";let times=document.createElement("div");times.className="times";
 for(let h=0;h<24;h++){let t=document.createElement("div");t.className="tick";t.style.top=(h*68)+"px";t.textContent=fmt(String(h).padStart(2,"0")+":00");times.appendChild(t)}br.appendChild(times);
 drivers.forEach(d=>{let lane=document.createElement("div");lane.className="lane";day.filter(x=>x.driver===d).forEach(x=>{let a=x.scheduled_time.split(":").map(Number),m=a[0]*60+a[1],b=document.createElement("button");b.className="card";b.style.top=((m/30)*34+2)+"px";b.innerHTML="<b>"+fmt(x.scheduled_time)+" · Job "+esc(x.job_number)+"</b><small>"+esc(x.origin)+" → "+esc(x.destination)+"</small><small>"+x.pallet_count+" pallets · 53' dry van</small><small>Built by "+esc(x.created_by_name)+"</small>";b.onclick=()=>edit(x.id);lane.appendChild(b)});br.appendChild(lane)});E.grid.appendChild(br);renderDrivers()
}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function renderUsers(list){E.active.innerHTML="";(list||[]).forEach(u=>{let d=document.createElement("div");d.className="activeRow";d.textContent=u.display_name||u.email||"User";E.active.appendChild(d)})}
async function load(){if(!live){loadLocal();renderBoard();return}let r=await sb.from("transfers").select("*").order("scheduled_date").order("scheduled_time");if(r.error){msg(r.error.message,"error");return}items=(r.data||[]).map(normalize);renderBoard()}
async function subscribe(){if(!live)return;sb.channel("transfers-table").on("postgres_changes",{event:"*",schema:"public",table:"transfers"},load).subscribe();
 presence=sb.channel("transfers-active",{config:{presence:{key:user.id}}}).on("presence",{event:"sync"},()=>{let a=[];Object.values(presence.presenceState()).forEach(v=>v.forEach(x=>a.push(x)));renderUsers(a)}).subscribe(async s=>{if(s==="SUBSCRIBED")await presence.track({user_id:user.id,display_name:name(),email:user.email})})}
function reset(){E.form.reset();E.edit.value="";E.date.value=E.boardDate.value;E.time.value="08:00";E.formTitle.textContent="Build Transfer Load";E.save.textContent="Add Transfer";E.del.classList.add("hidden");E.cancel.classList.add("hidden");msg("")}
function edit(id){let x=items.find(i=>i.id===String(id));if(!x)return;E.edit.value=x.id;E.date.value=x.scheduled_date;E.time.value=x.scheduled_time;E.driver.value=x.driver;E.origin.value=x.origin;E.destination.value=x.destination;E.pallet.value=x.pallet_count;E.job.value=x.job_number;E.formTitle.textContent="Edit Transfer Load";E.save.textContent="Update Transfer";E.del.classList.remove("hidden");E.cancel.classList.remove("hidden");msg("Created by "+x.created_by_name)}
async function submit(ev){ev.preventDefault();let p={scheduled_date:E.date.value,scheduled_time:E.time.value,driver:E.driver.value.trim(),origin:E.origin.value.trim(),destination:E.destination.value.trim(),pallet_count:Number(E.pallet.value),job_number:E.job.value.trim(),created_by:user?.id||"demo-user",created_by_name:name()};if(!p.scheduled_date||!p.scheduled_time||!p.driver||!p.origin||!p.destination||!p.job_number||Number.isNaN(p.pallet_count)){msg("Complete all fields.","error");return}if(p.origin.toLowerCase()===p.destination.toLowerCase()){msg("Origination and destination must be different.","error");return}
 let id=E.edit.value;
 if(live){let r=id?await sb.from("transfers").update({scheduled_date:p.scheduled_date,scheduled_time:p.scheduled_time,driver:p.driver,origin:p.origin,destination:p.destination,pallet_count:p.pallet_count,job_number:p.job_number,updated_at:new Date().toISOString()}).eq("id",id):await sb.from("transfers").insert(p);if(r.error){msg(r.error.message,"error");return}await load()}
 else{if(id){let i=items.findIndex(x=>x.id===id);if(i>=0)items[i]={...items[i],...p}}else items.push(normalize({...p,id:crypto.randomUUID?crypto.randomUUID():String(Date.now())}));saveLocal();renderBoard()}
 E.boardDate.value=p.scheduled_date;reset();renderBoard();msg(id?"Transfer updated.":"Transfer added.","ok")
}
async function remove(){let id=E.edit.value;if(!id||!confirm("Delete this transfer load?"))return;if(live){let r=await sb.from("transfers").delete().eq("id",id);if(r.error){msg(r.error.message,"error");return}await load()}else{items=items.filter(x=>x.id!==id);saveLocal();renderBoard()}reset();msg("Transfer deleted.","ok")}
async function session(s){if(!s?.user){user=null;E.login.classList.remove("hidden");return}user=s.user;E.login.classList.add("hidden");E.signout.classList.remove("hidden");let r=await sb.from("profiles").select("display_name").eq("id",user.id).maybeSingle();profile=r.data||{display_name:user.email?.split("@")[0]||"User"};E.me.textContent=name();E.email.textContent=user.email||"";await subscribe();await load()}
E.form.onsubmit=submit;E.del.onclick=remove;E.cancel.onclick=reset;$("prev").onclick=()=>{E.boardDate.value=add(E.boardDate.value,-1);E.date.value=E.boardDate.value;renderBoard()};$("next").onclick=()=>{E.boardDate.value=add(E.boardDate.value,1);E.date.value=E.boardDate.value;renderBoard()};$("today").onclick=()=>{E.boardDate.value=today();E.date.value=E.boardDate.value;renderBoard()};E.boardDate.onchange=()=>{E.date.value=E.boardDate.value;renderBoard()};E.signout.onclick=()=>sb?.auth.signOut();
E.loginForm.onsubmit=async e=>{e.preventDefault();E.loginMsg.textContent="Signing in…";let r=await sb.auth.signInWithPassword({email:E.loginEmail.value.trim(),password:E.loginPassword.value});E.loginMsg.textContent=r.error?r.error.message:""};
(async()=>{E.boardDate.value=today();E.date.value=today();E.time.value="08:00";if(!live){user={id:"demo-user",email:"Local preview mode",user_metadata:{display_name:"Demo User"}};profile={display_name:"Demo User"};renderUsers([{display_name:"Demo User"}]);loadLocal();renderBoard();return}E.mode.textContent="Live";let s=await sb.auth.getSession();await session(s.data.session);sb.auth.onAuthStateChange((_e,s)=>session(s))})();
})();