(()=>{
const C=window.TRANSFERS_CONFIG||{},live=!!(C.supabaseUrl&&C.supabaseAnonKey),sb=live?window.supabase.createClient(C.supabaseUrl,C.supabaseAnonKey):null;
let user=null,profile=null,items=[],drivers=[],locations=[],presence=null,dataChannel=null,optionContext=null,ignoreClickUntil=0;
const $=id=>document.getElementById(id),E={form:$("form"),edit:$("editId"),date:$("date"),time:$("time"),duration:$("duration"),driver:$("driver"),origin:$("origin"),destination:$("destination"),pallet:$("pallet"),job:$("job"),save:$("save"),del:$("delete"),cancel:$("cancel"),msg:$("msg"),boardDate:$("boardDate"),grid:$("grid"),title:$("title"),mode:$("mode"),me:$("me"),email:$("email"),active:$("active"),login:$("login"),loginForm:$("loginForm"),loginEmail:$("loginEmail"),loginPassword:$("loginPassword"),loginMsg:$("loginMsg"),signout:$("signout"),formTitle:$("formTitle"),optionModal:$("optionModal"),optionForm:$("optionForm"),optionTitle:$("optionTitle"),optionLabel:$("optionLabel"),optionName:$("optionName"),optionMsg:$("optionMsg"),optionClose:$("optionClose"),optionCancel:$("optionCancel")};
const key="transfers-demo-v2",driverKey="transfers-demo-drivers-v1",locationKey="transfers-demo-locations-v1",PX15=17;
const today=()=>{let d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)},add=(iso,n)=>{let d=new Date(iso+"T12:00:00");d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)},fmt=t=>{let [h,m]=String(t).slice(0,5).split(":").map(Number);return (h%12||12)+":"+String(m).padStart(2,"0")+" "+(h>=12?"PM":"AM")};
const minToTime=m=>String(Math.floor(m/60)).padStart(2,"0")+":"+String(m%60).padStart(2,"0"),timeToMin=t=>{let [h,m]=String(t).slice(0,5).split(":").map(Number);return h*60+m};
function name(){return profile?.display_name||user?.user_metadata?.display_name||user?.email?.split("@")[0]||"User"}
function msg(s,c){E.msg.textContent=s||"";E.msg.style.color=c==="error"?"#a43c3c":c==="ok"?"#2f6f49":""}
function optionMsg(s,c){E.optionMsg.textContent=s||"";E.optionMsg.style.color=c==="error"?"#a43c3c":c==="ok"?"#2f6f49":""}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function normalize(x){return{id:String(x.id),scheduled_date:x.scheduled_date,scheduled_time:String(x.scheduled_time||"00:00").slice(0,5),duration_minutes:Number(x.duration_minutes||60),driver:x.driver||"Unassigned",origin:x.origin||"",destination:x.destination||"",pallet_count:Number(x.pallet_count||0),job_number:x.job_number||"",order_status:x.order_status||"Loading",move_number:x.move_number==null?null:Number(x.move_number),created_by:x.created_by,created_by_name:x.created_by_name||"Unknown"}}
function uniq(values){return [...new Set(values.filter(Boolean).map(v=>String(v).trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b))}
function saveLocal(){localStorage.setItem(key,JSON.stringify(items));localStorage.setItem(driverKey,JSON.stringify(drivers));localStorage.setItem(locationKey,JSON.stringify(locations))}
function loadLocal(){try{items=(JSON.parse(localStorage.getItem(key)||"[]")||[]).map(normalize)}catch{items=[]}try{drivers=JSON.parse(localStorage.getItem(driverKey)||"[]")||[]}catch{drivers=[]}try{locations=JSON.parse(localStorage.getItem(locationKey)||'["Building 100","Building 200"]')||[]}catch{locations=["Building 100","Building 200"]}drivers=uniq([...drivers,...items.map(x=>x.driver)]);locations=uniq([...locations,...items.flatMap(x=>[x.origin,x.destination]),"Building 100","Building 200"])}
function fillSelect(select,values,placeholder,addText,sentinel,preserve){let current=preserve??select.value;select.innerHTML='<option value="" disabled>'+esc(placeholder)+'</option>'+values.map(v=>'<option value="'+esc(v)+'">'+esc(v)+'</option>').join("")+'<option value="'+sentinel+'">＋ '+esc(addText)+'</option>';if(values.includes(current))select.value=current;else select.value=""}
function renderOptions(){let dv=E.driver.value,ov=E.origin.value,tv=E.destination.value;fillSelect(E.driver,drivers,"Select driver","Add a Driver…","__add_driver__",dv);fillSelect(E.origin,locations,"Select origin","Add a Location…","__add_location__",ov);fillSelect(E.destination,locations,"Select destination","Add a Location…","__add_location__",tv)}
function renderUsers(list){E.active.innerHTML="";(list||[]).forEach(u=>{let d=document.createElement("div");d.className="activeRow";d.textContent=u.display_name||u.email||"User";E.active.appendChild(d)})}
function renderBoard(){
 const date=E.boardDate.value,day=items.filter(x=>x.scheduled_date===date),laneDrivers=uniq([...drivers,...day.map(x=>x.driver)]);
 E.title.textContent=new Date(date+"T12:00:00").toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric",year:"numeric"});E.grid.innerHTML="";
 const hr=document.createElement("div");hr.className="headrow";const c=document.createElement("div");c.className="corner";c.textContent="Time";hr.appendChild(c);
 if(!laneDrivers.length){let d=document.createElement("div");d.className="driverhead";d.textContent="Add a driver to begin";hr.appendChild(d)}
 laneDrivers.forEach(d=>{let h=document.createElement("div");h.className="driverhead";h.textContent=d;hr.appendChild(h)});E.grid.appendChild(hr);
 const br=document.createElement("div");br.className="bodyrow";const times=document.createElement("div");times.className="times";
 for(let h=0;h<24;h++){let t=document.createElement("div");t.className="tick";t.style.top=(h*68)+"px";t.textContent=fmt(String(h).padStart(2,"0")+":00");times.appendChild(t)}br.appendChild(times);
 if(!laneDrivers.length){let empty=document.createElement("div");empty.className="emptylane";empty.textContent="Use the Driver dropdown to add your first driver.";br.appendChild(empty)}
 laneDrivers.forEach(d=>{let lane=document.createElement("div");lane.className="lane";lane.dataset.driver=d;lane.addEventListener("dragover",e=>{e.preventDefault();lane.classList.add("dragover")});lane.addEventListener("dragleave",()=>lane.classList.remove("dragover"));lane.addEventListener("drop",dropCard);day.filter(x=>x.driver===d).forEach(x=>lane.appendChild(makeCard(x)));br.appendChild(lane)});E.grid.appendChild(br)
}
function makeCard(x){let m=timeToMin(x.scheduled_time),b=document.createElement("button");b.type="button";b.className="card";b.draggable=true;b.dataset.id=x.id;b.style.top=((m/15)*PX15+2)+"px";b.style.height=Math.max(22,(x.duration_minutes/15)*PX15-4)+"px";b.innerHTML='<span class="draghint">↕</span><span class="card-status">'+esc(x.order_status||"Loading")+'</span><b>Move #'+esc(x.move_number??"—")+' · '+fmt(x.scheduled_time)+' · Job '+esc(x.job_number)+'</b><small>'+esc(x.origin)+' → '+esc(x.destination)+'</small><small>'+x.pallet_count+' pallets · '+durationLabel(x.duration_minutes)+' · 53\' dry van</small><small>Built by '+esc(x.created_by_name)+'</small>';b.addEventListener("dragstart",e=>{ignoreClickUntil=Date.now()+500;b.classList.add("dragging");e.dataTransfer.effectAllowed="move";e.dataTransfer.setData("text/plain",x.id)});b.addEventListener("dragend",()=>b.classList.remove("dragging"));b.onclick=()=>{if(Date.now()<ignoreClickUntil)return;edit(x.id)};return b}
function durationLabel(n){if(n<60)return n+" min";let h=Math.floor(n/60),m=n%60;return h+" hr"+(h!==1?"s":"")+(m?" "+m+" min":"")}
async function dropCard(e){e.preventDefault();const lane=e.currentTarget;lane.classList.remove("dragover");const id=e.dataTransfer.getData("text/plain");const x=items.find(i=>i.id===id);if(!x)return;const rect=lane.getBoundingClientRect(),raw=Math.round((e.clientY-rect.top)/PX15)*15,max=Math.max(0,1440-x.duration_minutes),minutes=Math.max(0,Math.min(max,raw)),newTime=minToTime(minutes),newDriver=lane.dataset.driver;await moveTransfer(x,newDriver,newTime)}
async function moveTransfer(x,newDriver,newTime){const old={driver:x.driver,scheduled_time:x.scheduled_time};x.driver=newDriver;x.scheduled_time=newTime;renderBoard();if(live){let r=await sb.from("transfers").update({driver:newDriver,scheduled_time:newTime,updated_at:new Date().toISOString()}).eq("id",x.id).select("*").single();if(r.error){x.driver=old.driver;x.scheduled_time=old.scheduled_time;renderBoard();msg("Could not move transfer: "+r.error.message,"error");return}replaceItem(r.data);renderBoard()}else saveLocal();msg("Transfer moved to "+fmt(newTime)+" with "+newDriver+".","ok")}
function replaceItem(row){const n=normalize(row),i=items.findIndex(x=>x.id===n.id);if(i>=0)items[i]=n;else items.push(n)}
async function loadData(){if(!live){loadLocal();renderOptions();renderBoard();return}const [tr,dr,lr]=await Promise.all([sb.from("transfers").select("*").order("scheduled_date").order("scheduled_time"),sb.from("transfer_drivers").select("name").order("name"),sb.from("transfer_locations").select("name").order("name")]);if(tr.error){msg("Transfers could not load: "+tr.error.message,"error");items=[]}else items=(tr.data||[]).map(normalize);drivers=uniq([...(dr.error?[]:(dr.data||[]).map(x=>x.name)),...items.map(x=>x.driver)]);locations=uniq([...(lr.error?["Building 100","Building 200"]:(lr.data||[]).map(x=>x.name)),...items.flatMap(x=>[x.origin,x.destination]),"Building 100","Building 200"]);if(dr.error||lr.error)msg("Driver/location lists need the latest schema.sql migration.","error");renderOptions();renderBoard()}
async function subscribe(){if(!live)return;if(dataChannel)await sb.removeChannel(dataChannel);if(presence)await sb.removeChannel(presence);dataChannel=sb.channel("transfers-data").on("postgres_changes",{event:"*",schema:"public",table:"transfers"},loadData).on("postgres_changes",{event:"*",schema:"public",table:"transfer_drivers"},loadData).on("postgres_changes",{event:"*",schema:"public",table:"transfer_locations"},loadData).subscribe();presence=sb.channel("transfers-active",{config:{presence:{key:user.id}}}).on("presence",{event:"sync"},()=>{let a=[];Object.values(presence.presenceState()).forEach(v=>v.forEach(x=>a.push(x)));renderUsers(a)}).subscribe(async s=>{if(s==="SUBSCRIBED")await presence.track({user_id:user.id,display_name:name(),email:user.email})})}
function reset(){E.form.reset();E.edit.value="";E.date.value=E.boardDate.value;E.time.value="08:00";E.duration.value="60";E.formTitle.textContent="Build Transfer Load";E.save.textContent="Add Transfer";E.del.classList.add("hidden");E.cancel.classList.add("hidden");renderOptions();msg("")}
function edit(id){let x=items.find(i=>i.id===String(id));if(!x)return;E.edit.value=x.id;E.date.value=x.scheduled_date;E.time.value=x.scheduled_time;E.duration.value=String(x.duration_minutes);renderOptions();E.driver.value=x.driver;E.origin.value=x.origin;E.destination.value=x.destination;E.pallet.value=x.pallet_count;E.job.value=x.job_number;E.formTitle.textContent="Edit Transfer Load";E.save.textContent="Update Transfer";E.del.classList.remove("hidden");E.cancel.classList.remove("hidden");msg("Created by "+x.created_by_name)}
async function submit(ev){ev.preventDefault();let p={scheduled_date:E.date.value,scheduled_time:E.time.value,duration_minutes:Number(E.duration.value),driver:E.driver.value,origin:E.origin.value,destination:E.destination.value,pallet_count:Number(E.pallet.value),job_number:E.job.value.trim(),created_by:user?.id||"demo-user",created_by_name:name()};if(!p.scheduled_date||!p.scheduled_time||!p.duration_minutes||!p.driver||p.driver.startsWith("__")||!p.origin||p.origin.startsWith("__")||!p.destination||p.destination.startsWith("__")||!p.job_number||Number.isNaN(p.pallet_count)){msg("Complete all fields.","error");return}if(p.origin.toLowerCase()===p.destination.toLowerCase()){msg("Origination and destination must be different.","error");return}let id=E.edit.value;
 if(live){let r;if(id){r=await sb.from("transfers").update({scheduled_date:p.scheduled_date,scheduled_time:p.scheduled_time,duration_minutes:p.duration_minutes,driver:p.driver,origin:p.origin,destination:p.destination,pallet_count:p.pallet_count,job_number:p.job_number,updated_at:new Date().toISOString()}).eq("id",id).select("*").single()}else{r=await sb.from("transfers").insert(p).select("*").single()}if(r.error){msg("Could not save transfer: "+r.error.message,"error");return}replaceItem(r.data)}else{if(id){let i=items.findIndex(x=>x.id===id);if(i>=0)items[i]={...items[i],...p}}else items.push(normalize({...p,id:crypto.randomUUID?crypto.randomUUID():String(Date.now())}));drivers=uniq([...drivers,p.driver]);locations=uniq([...locations,p.origin,p.destination]);saveLocal()}
 E.boardDate.value=p.scheduled_date;renderOptions();renderBoard();reset();msg(id?"Transfer updated.":"Transfer added.","ok")
}
async function remove(){let id=E.edit.value;if(!id||!confirm("Delete this transfer load?"))return;if(live){let r=await sb.from("transfers").delete().eq("id",id);if(r.error){msg(r.error.message,"error");return}}items=items.filter(x=>x.id!==id);if(!live)saveLocal();renderBoard();reset();msg("Transfer deleted.","ok")}
function managedChange(kind,select){if(select.value==="__add_driver__")openOption("driver",select);else if(select.value==="__add_location__")openOption("location",select)}
function openOption(kind,select){optionContext={kind,select};E.optionTitle.textContent=kind==="driver"?"Add a Driver":"Add a Location";E.optionLabel.firstChild.textContent=kind==="driver"?"Driver Name":"Building / Location Name";E.optionName.value="";optionMsg("");E.optionModal.classList.remove("hidden");setTimeout(()=>E.optionName.focus(),0)}
function closeOption(){if(optionContext?.select&&optionContext.select.value.startsWith("__"))optionContext.select.value="";optionContext=null;E.optionModal.classList.add("hidden");optionMsg("")}
async function addOption(ev){ev.preventDefault();if(!optionContext)return;const value=E.optionName.value.trim(),kind=optionContext.kind,list=kind==="driver"?drivers:locations;if(!value){optionMsg("Enter a name.","error");return}const existing=list.find(x=>x.toLowerCase()===value.toLowerCase());if(existing){renderOptions();optionContext.select.value=existing;closeOption();return}if(live){const table=kind==="driver"?"transfer_drivers":"transfer_locations",r=await sb.from(table).insert({name:value,created_by:user.id,created_by_name:name()}).select("name").single();if(r.error){optionMsg("Could not add option: "+r.error.message,"error");return}}if(kind==="driver")drivers=uniq([...drivers,value]);else locations=uniq([...locations,value]);if(!live)saveLocal();const target=optionContext.select;renderOptions();target.value=value;closeOption();renderBoard()}
async function session(s){if(!s?.user){user=null;E.login.classList.remove("hidden");return}user=s.user;E.login.classList.add("hidden");E.signout.classList.remove("hidden");let r=await sb.from("profiles").select("display_name").eq("id",user.id).maybeSingle();profile=r.data||{display_name:user.email?.split("@")[0]||"User"};E.me.textContent=name();E.email.textContent=user.email||"";await loadData();await subscribe()}
E.form.onsubmit=submit;E.del.onclick=remove;E.cancel.onclick=reset;E.driver.onchange=()=>managedChange("driver",E.driver);E.origin.onchange=()=>managedChange("location",E.origin);E.destination.onchange=()=>managedChange("location",E.destination);E.optionForm.onsubmit=addOption;E.optionClose.onclick=closeOption;E.optionCancel.onclick=closeOption;E.optionModal.addEventListener("click",e=>{if(e.target===E.optionModal)closeOption()});
$("prev").onclick=()=>{E.boardDate.value=add(E.boardDate.value,-1);E.date.value=E.boardDate.value;renderBoard()};$("next").onclick=()=>{E.boardDate.value=add(E.boardDate.value,1);E.date.value=E.boardDate.value;renderBoard()};$("today").onclick=()=>{E.boardDate.value=today();E.date.value=E.boardDate.value;renderBoard()};E.boardDate.onchange=()=>{E.date.value=E.boardDate.value;renderBoard()};E.signout.onclick=()=>sb?.auth.signOut();
E.loginForm.onsubmit=async e=>{e.preventDefault();E.loginMsg.textContent="Signing in…";let r=await sb.auth.signInWithPassword({email:E.loginEmail.value.trim(),password:E.loginPassword.value});E.loginMsg.textContent=r.error?r.error.message:""};
(async()=>{E.boardDate.value=today();E.date.value=today();E.time.value="08:00";E.duration.value="60";if(!live){user={id:"demo-user",email:"Local preview mode",user_metadata:{display_name:"Demo User"}};profile={display_name:"Demo User"};renderUsers([{display_name:"Demo User"}]);loadLocal();renderOptions();renderBoard();return}E.mode.textContent="Live";let s=await sb.auth.getSession();await session(s.data.session);sb.auth.onAuthStateChange((_e,s)=>session(s))})();
})();