-- Transfers v8: Team Chat
-- Safe to run more than once.

create table if not exists public.transfer_chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  user_name text not null default 'User',
  user_email text,
  message text not null check (char_length(message) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.transfer_chat_messages enable row level security;

drop policy if exists "transfer chat read" on public.transfer_chat_messages;
create policy "transfer chat read"
on public.transfer_chat_messages
for select
to authenticated
using (true);

drop policy if exists "transfer chat insert" on public.transfer_chat_messages;
create policy "transfer chat insert"
on public.transfer_chat_messages
for insert
to authenticated
with check (auth.uid() = user_id);

grant select, insert on public.transfer_chat_messages to authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='transfer_chat_messages'
  ) then
    alter publication supabase_realtime add table public.transfer_chat_messages;
  end if;
end $$;

select pg_notify('pgrst', 'reload schema');
