-- Transfers v4: Recent Activity history
-- Safe to run more than once.

alter table public.transfers
  add column if not exists order_status text not null default 'Loading';

create table if not exists public.transfer_activity (
  id bigint generated by default as identity primary key,
  transfer_id uuid,
  action text not null,
  actor_id uuid,
  actor_name text not null default 'User',
  job_number text,
  driver text,
  details text,
  created_at timestamptz not null default now()
);

alter table public.transfer_activity enable row level security;

drop policy if exists "transfer activity read" on public.transfer_activity;
create policy "transfer activity read"
on public.transfer_activity
for select
to authenticated
using (true);

grant select on public.transfer_activity to authenticated;

create or replace function public.log_transfer_activity()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_actor_id uuid;
  v_actor_name text;
  v_action text;
  v_details text;
  v_row public.transfers%rowtype;
begin
  v_actor_id := auth.uid();

  select display_name into v_actor_name
  from public.profiles
  where id = v_actor_id;

  if tg_op = 'DELETE' then
    v_row := old;
    v_action := 'Deleted';
    v_details := coalesce(old.origin,'') || ' → ' || coalesce(old.destination,'');
  elsif tg_op = 'INSERT' then
    v_row := new;
    v_action := 'Created';
    v_details := coalesce(new.origin,'') || ' → ' || coalesce(new.destination,'');
  else
    v_row := new;

    if old.order_status is distinct from new.order_status then
      v_action := 'Status changed';
      v_details := coalesce(old.order_status,'') || ' → ' || coalesce(new.order_status,'');
    elsif old.driver is distinct from new.driver
       or old.scheduled_date is distinct from new.scheduled_date
       or old.scheduled_time is distinct from new.scheduled_time then
      v_action := 'Rescheduled';
      v_details := coalesce(new.scheduled_date::text,'') || ' ' ||
                   coalesce(left(new.scheduled_time::text,5),'') ||
                   case when old.driver is distinct from new.driver
                        then ' · Driver: ' || coalesce(new.driver,'')
                        else '' end;
    elsif old.duration_minutes is distinct from new.duration_minutes
       or old.origin is distinct from new.origin
       or old.destination is distinct from new.destination
       or old.pallet_count is distinct from new.pallet_count
       or old.job_number is distinct from new.job_number then
      v_action := 'Updated';
      v_details := coalesce(new.origin,'') || ' → ' || coalesce(new.destination,'');
    else
      return new;
    end if;
  end if;

  v_actor_name := coalesce(
    nullif(v_actor_name,''),
    nullif(v_row.created_by_name,''),
    'User'
  );

  insert into public.transfer_activity(
    transfer_id, action, actor_id, actor_name,
    job_number, driver, details
  )
  values(
    v_row.id, v_action, v_actor_id, v_actor_name,
    v_row.job_number, v_row.driver, v_details
  );

  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

drop trigger if exists transfer_activity_trigger on public.transfers;
create trigger transfer_activity_trigger
after insert or update or delete on public.transfers
for each row execute function public.log_transfer_activity();

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='transfer_activity'
  ) then
    alter publication supabase_realtime add table public.transfer_activity;
  end if;
end $$;

select pg_notify('pgrst', 'reload schema');
