-- Transfers: Drivers page recent history.
-- Safe to run more than once.

create table if not exists public.driver_activity(
  id bigint generated by default as identity primary key,
  driver_name text,
  action text not null,
  details text,
  actor_id uuid references auth.users(id),
  actor_name text not null default 'User',
  created_at timestamptz not null default now()
);

alter table public.driver_activity enable row level security;

drop policy if exists "driver activity read" on public.driver_activity;
create policy "driver activity read"
  on public.driver_activity for select
  to authenticated
  using(true);

drop policy if exists "driver activity insert" on public.driver_activity;
create policy "driver activity insert"
  on public.driver_activity for insert
  to authenticated
  with check((select auth.uid())=actor_id);

grant select, insert on public.driver_activity to authenticated;

do $$
begin
  if not exists(
    select 1
    from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='driver_activity'
  ) then
    alter publication supabase_realtime add table public.driver_activity;
  end if;
end $$;

notify pgrst, 'reload schema';