-- Transfers v9: Driver SMS
-- Safe to run more than once.

alter table public.transfer_drivers
  add column if not exists phone_number text;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'transfer_drivers_phone_number_check'
      and conrelid = 'public.transfer_drivers'::regclass
  ) then
    alter table public.transfer_drivers
      add constraint transfer_drivers_phone_number_check
      check (
        phone_number is null
        or phone_number ~ '^\+[1-9][0-9]{7,14}$'
      );
  end if;
end $$;

create table if not exists public.transfer_sms_log (
  id bigint generated by default as identity primary key,
  transfer_id uuid references public.transfers(id) on delete set null,
  driver text not null,
  to_number text not null,
  message text not null check (char_length(message) between 1 and 1600),
  message_type text not null default 'custom',
  provider_message_sid text,
  provider_status text,
  actor_id uuid references auth.users(id) on delete set null,
  actor_name text not null default 'User',
  created_at timestamptz not null default now()
);

create index if not exists transfer_sms_log_transfer_created_idx
  on public.transfer_sms_log(transfer_id, created_at desc);

alter table public.transfer_sms_log enable row level security;

drop policy if exists "transfer sms log read" on public.transfer_sms_log;
create policy "transfer sms log read"
on public.transfer_sms_log
for select
to authenticated
using (true);

grant select on public.transfer_sms_log to authenticated;

select pg_notify('pgrst', 'reload schema');
