create extension if not exists pgcrypto;

create table if not exists public.profiles(
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'User',
  updated_at timestamptz not null default now()
);

create table if not exists public.transfers(
  id uuid primary key default gen_random_uuid(),
  scheduled_date date not null,
  scheduled_time time not null,
  duration_minutes int not null default 120,
  driver text not null,
  origin text not null,
  destination text not null,
  pallet_count int not null default 0 check(pallet_count>=0),
  job_number text not null,
  order_status text not null default 'Loading',
  created_by uuid not null references auth.users(id),
  created_by_name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.transfers add column if not exists duration_minutes int not null default 120;
alter table public.transfers alter column duration_minutes set default 120;
alter table public.transfers add column if not exists order_status text not null default 'Loading';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname='transfers_duration_minutes_check'
      and conrelid='public.transfers'::regclass
  ) then
    alter table public.transfers add constraint transfers_duration_minutes_check check(duration_minutes between 15 and 720);
  end if;
end $$;

create table if not exists public.transfer_drivers(
  name text primary key,
  created_by uuid references auth.users(id) on delete set null,
  created_by_name text not null default 'System',
  sort_order integer not null default 1000000,
  phone_number text,
  created_at timestamptz not null default now()
);

alter table public.transfer_drivers
  add column if not exists sort_order integer not null default 1000000;

alter table public.transfer_drivers
  add column if not exists phone_number text;

insert into public.transfer_drivers(name,created_by_name,sort_order)
values ('Planning','System',-1)
on conflict(name) do nothing;

create table if not exists public.transfer_locations(
  name text primary key,
  created_by uuid references auth.users(id) on delete set null,
  created_by_name text not null default 'System',
  created_at timestamptz not null default now()
);

create table if not exists public.transfer_chat_messages(
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  user_name text not null default 'User',
  user_email text,
  message text not null check (char_length(message) between 1 and 500),
  created_at timestamptz not null default now()
);

create table if not exists public.transfer_sms_log(
  id bigint generated by default as identity primary key,
  transfer_id uuid references public.transfers(id) on delete set null,
  driver text not null,
  to_number text not null,
  message text not null check (char_length(message) between 1 and 1600),
  message_type text not null default 'custom',
  provider_message_sid text,
  provider_status text,
  actor_id uuid references auth.users(id) on delete set null,
  actor_name text not null default 'User',
  created_at timestamptz not null default now()
);

create index if not exists transfer_sms_log_transfer_created_idx
  on public.transfer_sms_log(transfer_id, created_at desc);

insert into public.transfer_locations(name,created_by_name)
values ('Building 100','System'),('Building 200','System')
on conflict(name) do nothing;

alter table public.profiles enable row level security;
alter table public.transfers enable row level security;
alter table public.transfer_drivers enable row level security;
alter table public.transfer_locations enable row level security;
alter table public.transfer_chat_messages enable row level security;
alter table public.transfer_sms_log enable row level security;

drop policy if exists "profiles read" on public.profiles;
create policy "profiles read" on public.profiles for select to authenticated using(true);
drop policy if exists "profiles own insert" on public.profiles;
create policy "profiles own insert" on public.profiles for insert to authenticated with check(auth.uid()=id);
drop policy if exists "profiles own update" on public.profiles;
create policy "profiles own update" on public.profiles for update to authenticated using(auth.uid()=id) with check(auth.uid()=id);

drop policy if exists "transfers read" on public.transfers;
create policy "transfers read" on public.transfers for select to authenticated using(true);
drop policy if exists "transfers insert" on public.transfers;
create policy "transfers insert" on public.transfers for insert to authenticated with check(auth.uid()=created_by);
drop policy if exists "transfers update" on public.transfers;
create policy "transfers update" on public.transfers for update to authenticated using(true) with check(true);
drop policy if exists "transfers delete" on public.transfers;
create policy "transfers delete" on public.transfers for delete to authenticated using(true);

drop policy if exists "transfer drivers read" on public.transfer_drivers;
create policy "transfer drivers read" on public.transfer_drivers for select to authenticated using(true);
drop policy if exists "transfer drivers insert" on public.transfer_drivers;
create policy "transfer drivers insert" on public.transfer_drivers for insert to authenticated with check(auth.uid()=created_by);

drop policy if exists "transfer locations read" on public.transfer_locations;
create policy "transfer locations read" on public.transfer_locations for select to authenticated using(true);
drop policy if exists "transfer locations insert" on public.transfer_locations;
create policy "transfer locations insert" on public.transfer_locations for insert to authenticated with check(auth.uid()=created_by);

drop policy if exists "transfer chat read" on public.transfer_chat_messages;
create policy "transfer chat read" on public.transfer_chat_messages for select to authenticated using(true);
drop policy if exists "transfer chat insert" on public.transfer_chat_messages;
create policy "transfer chat insert" on public.transfer_chat_messages for insert to authenticated with check(auth.uid()=user_id);

grant select, insert on public.transfer_chat_messages to authenticated;
grant usage, select on sequence public.transfer_chat_messages_id_seq to authenticated;

drop policy if exists "transfer sms log read" on public.transfer_sms_log;
create policy "transfer sms log read" on public.transfer_sms_log for select to authenticated using(true);
grant select on public.transfer_sms_log to authenticated;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  insert into public.profiles(id,display_name)
  values(new.id,coalesce(new.raw_user_meta_data->>'display_name',split_part(new.email,'@',1),'User'))
  on conflict(id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

insert into public.profiles(id,display_name)
select id,coalesce(raw_user_meta_data->>'display_name',split_part(email,'@',1),'User')
from auth.users
on conflict(id) do nothing;

do $$
begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='transfers') then alter publication supabase_realtime add table public.transfers; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='transfer_drivers') then alter publication supabase_realtime add table public.transfer_drivers; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='transfer_locations') then alter publication supabase_realtime add table public.transfer_locations; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='transfer_chat_messages') then alter publication supabase_realtime add table public.transfer_chat_messages; end if;
end $$;

create or replace function public.reorder_transfer_drivers(p_names text[])
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text;
  v_pos integer := 0;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;
  foreach v_name in array p_names loop
    update public.transfer_drivers set sort_order = v_pos where name = v_name;
    v_pos := v_pos + 1;
  end loop;
end;
$$;

grant execute on function public.reorder_transfer_drivers(text[]) to authenticated;
